// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css"; // Nếu có dùng css global
import 'bootstrap/dist/css/bootstrap.min.css'; // Import Bootstrap của bạn ở đây (nếu dùng)
import { Header } from "../layouts/Header";
import { Footer } from "../layouts/Footer";
import "bootstrap/dist/css/bootstrap.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export interface UserDto {
  id: string;
  userName: string;
  email: string;
  // Thêm các trường khác nếu cần
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
          <Header />
          <main style={{ flex: 1 }}>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}