// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css"; // Nếu có dùng css global
import "bootstrap/dist/css/bootstrap.min.css"; // Import Bootstrap của bạn ở đây (nếu dùng)
import { Header } from "../layouts/Header";
import { Footer } from "../layouts/Footer";
import "bootstrap/dist/css/bootstrap.min.css";
import { LayoutProvider } from "../contexts/LayoutContext";
import { ReduxProvider } from "../store/ReduxProvider";
import Toast from "../components/Toast/Toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Welcome to POG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <LayoutProvider>
            <Toast />
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                minHeight: "100vh",
              }}
            >
              <Header />
              <main style={{ flex: 1 }}>{children}</main>
              <Footer />
            </div>
          </LayoutProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
