// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css"; // Nếu có dùng css global
import 'bootstrap/dist/css/bootstrap.min.css'; // Import Bootstrap của bạn ở đây (nếu dùng)
import { Header } from "../layouts/Header";
import { Footer } from "../layouts/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Header />
      <body className={inter.className}>
  
        {children}
      </body>
      <Footer />
    </html>
  );
}